variables:
  AZURE_SERVICE: indexer-queue
  AZURE_BUILD_SUBDIR: indexer-queue-azure-enqueue
  AZURE_TEST_SUBDIR: testing/indexer-queue-azure-enqueue
  AZURE_SKIP_SWAGGER_TEST: "true"

  GCP_BUILD_SUBDIR: indexer-queue-gcp
  GCP_INT_TEST_SUBDIR: indexer-queue-gcp # Fix as soon as integration tests are added
  GCP_APPLICATION_NAME: osdu-indexer-queue
  GCP_ENVIRONMENT: testing
  GCP_PROJECT: opendes-evt
  GCP_TENANT_NAME: opendesevt
  GCP_DEPLOY_ENV: p4d
  GCP_DOMAIN: cloud.slb-ds.com

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "publishing/pages.yml"


gemnasium-maven-dependency_scanning:
  variables:
    DS_JAVA_VERSION: 17

azure_containerize:
  variables:
    AZURE_CONTAINERIZE_REPOSITORY: "https://gitlab-ci-token:${CI_JOB_TOKEN}@community.opengroup.org/osdu/platform/deployment-and-operations/base-containers-azure/service-base-image"

azure_test:
  image: community.opengroup.org:5555/osdu/platform/deployment-and-operations/base-containers-azure/azure-maven17:v0.0.1

fossa-analyze:
  image: $CI_REGISTRY/divido/fossa-with-cache:v0.9-jdk17
fossa-check-notice:
  image: $CI_REGISTRY/divido/fossa-with-cache:v0.9-jdk17